### ISSUE TITLE
how to train the pca file?

### ISSUE THREAD

**Issue by chensjtu** [cientgu/GIQA#1]
请问你这个pca文件是怎么训练出来的呢

**Comment by cientgu** [comment]
you can get it with the extract feature script:
python write_act.py path/to/dataset --act_path path/to/activation --pca_rate pca_rate --pca_path path/to/pca --gpu gpu_id

**Comment by chensjtu** [comment]
OK！
many thanks for the instruction. it seems as if i've got something wrong with the '.pkl'. the final score of the images will be stored inthe 'results.pkl'?

**Comment by cientgu** [comment]
The final score will be stored in the the output_file path, which you can name it as results.txt.
