### ISSUE TITLE
Two questions about write_act.py

### ISSUE THREAD

**Issue by cedricgsh** [cientgu/GIQA#3]
“”“python write_act.py path/to/dataset --act_path path/to/activation --pca_rate pca_rate --pca_path path/to/pca --gpu gpu_id”“”
1)The first parameter is "path/to/dataset". Do I need to use training dataset to get activation, or just apply a test dataset can get it.
2)The second parameter is "act_path". The write_act.py is used to generate the activation, and why you apply activation when generates it ? Or this path means a directory to save the activation generated by write_act.py.

**Comment by cientgu** [comment]
1. You need the training set of your GAN model to get the activation.
2. Yes, act_path means the directory to save the activation generated by write_act.py.
